### ISSUE TITLE
Contentful deployment to production requires a code deployment

### ISSUE THREAD

**Issue by david-raine** [WeAreBeep/FrontLineLive#26]
As currently configured, deployment of contentful changes to production requires a new "Space ID".  This means that a change needs to be made to the production secret CONTENTFUL_SPACE_ID and then a new deployment needs to be triggered. 

Is there any way that this dependency can be removed?

**Comment by jasonho215** [comment]
AFAIK Contentful Space ID is the ID of a project under the organisation and we don't need to change the ID when there's deployment of Contentful changes.

Contentful provides [environment management](https://www.contentful.com/developers/docs/tutorials/cli/environment-management/) that allow us to keep snapshots of project and alias a particular snapshot to an environment alias through Contentful portal, API, or CLI. Right now the production secret `CONTENTFUL_ENVIRONMENT` is an environment alias and we don't need to update the alias in production secret when there's deployment of Contentful changes.

**Comment by david-raine** [comment]
Thanks
